### ISSUE TITLE
Highlight which personnel and material treats which patient

### ISSUE THREAD

**Issue by Dassderdie** [hpi-sam/digital-fuesim-manv#205]

**Comment by lukasrad02** [comment]
@Dassderdie why has this issue been closed? As far as I can see, #222 did only add connections between patients and the personnel/material they're catering for while this issue requests connections between vehicles and their personnel/material.

We have received a feature request by a user to add such a feature and found this issue, so we do not want to create a new issue for the feature request until we know what caused closing this one without adding the feature.

**Comment by Dassderdie** [comment]
> @Dassderdie why has this issue been closed? As far as I can see, #222 did only add connections between patients and the personnel/material they're catering for while this issue requests connections between vehicles and their personnel/material.

I believe the name of this issue was incorrect. I changed it to reflect the changes that were actually made in connection with it.

> We have received a feature request by a user to add such a feature and found this issue, so we do not want to create a new issue for the feature request until we know what caused closing this one without adding the feature.

You should create a new issue for this. I believe we fulfilled the functionality only via the callsigns of the vehicles/materials/personnel.
