### ISSUE TITLE
Improve DOS protection against errors in reducers

### ISSUE THREAD

**Issue by Dassderdie** [hpi-sam/digital-fuesim-manv#225]
We often have DOS attacks in our reducers. These occur when we don't check for e.g. a correct id and try to access an object that doesn't exist. Currently, one such error would propagate all the way up and causes the complete server to crash.

To reduce the effects of one such error I propose to

1. Catch all errors from an reducer in production mode. In development we still only catch the `ReducerErrors` to spot them.

2. Isolate exercises from each other. The best would here probably be to run them in separate threads (performance boost). This is optional I guess because the reward is lower and the cost is substantially higher.

**Comment by ClFeSc** [comment]
Done via #325
