### ISSUE TITLE
Be able to insert shared link into exercise ID field

### ISSUE THREAD

**Issue by anonym-HPI** [hpi-sam/digital-fuesim-manv#247]
Right now, if you try to copy an ID from `https://example.com/exercise/123456` it only fills in `https://` and says `Die Eingabe darf nur Zahlen enthalten.` (only numbers are allowed to be entered).

A way that checks via regex if it is a valid URI and cuting out the last ID digits and paste the ID into the field would be good.

Example:
Inserting `https://example.com/exercise/123456` should be translated to `123456 ` and the field should be filled with it (is visible).

**Comment by christianzoellner** [comment]
Probably not needed very often, but might avoid some confusion for some users.

Ideally detect if text contains a proper URL and then extract and trip number from URL.
