### ISSUE TITLE
Better contrast for viewport

### ISSUE THREAD

**Issue by ClFeSc** [hpi-sam/digital-fuesim-manv#316]
To have better contrast, you could do two styles: a black stroke with a width `4` and the white one above with width `2`.

The problem is that this would further complicate the resizing logic -> probably not for now...

_Originally posted by @Dassderdie in https://github.com/hpi-sam/digital-fuesim-manv/pull/289#discussion_r857038811_

**Comment by christianzoellner** [comment]
due to expected difficulty (openLaysers) and questionable benefits (never occurred once in all testruns) close this issue
