### ISSUE TITLE
Lock MapImages

### ISSUE THREAD

**Issue by ClFeSc** [hpi-sam/digital-fuesim-manv#332]
Currently, when a mapImage takes up the whole screen, no movement for trainers with the mouse is possible. There should be a way to still move, e.g. by locking the mapImage.

**Comment by lukasrad02** [comment]
We're currently working on this and do not find the right place in the code to disable movements.

Taking a look at `frontend/src/app/pages/exercises/exercise/shared/exercise-map/feature-managers/map-images-feature-manager.ts`, there is a `onFeatueClicked`-handler, but this does not get triggered when you move the image.  
There also is the arrow function for `proposeMovementAction` passed to the super constructor, but passing an empty function just prevents sending the proposal to the server, not the movement itself.

Comparing the map image feature (which *cannot* be moved by a participant) to the vehicle feature (which *can* be moved by a participant), we did not find any differences that could reveal some kind of locking mechanism.

Even the `translatestart`-listener, registered in `frontend/src/app/pages/exercises/exercise/shared/exercise-map/utility/translate-helper.ts`, does not fire when a participant tries to drag an image, so the locking mechanism seems to be implemented earlier.

Could someone please give us a hint how to implement a locking mechanism?

**Comment by Dassderdie** [comment]
> Could someone please give us a hint how to implement a locking mechanism?

I'll look into this, this evening - please try a different issue in the meantime. This one is a bit trickier than I anticipated :/
