### ISSUE TITLE
Enable noUncheckedIndexedAccess in tsconfigs

### ISSUE THREAD

**Issue by Dassderdie** [hpi-sam/digital-fuesim-manv#358]
See https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess .
For some reason this option is not in the `strict` group.

This would improve the type safety, but requires (probably?) a lot of refactoring/non-null-assertions.

**Comment by ClFeSc** [comment]
I tested it: In the `backend`, it would be fine. In the `frontend` it requires much refactoring I think, and in `shared` it seems to be manageable.
