### ISSUE TITLE
Disallow zooming the whole interface and only the map

### ISSUE THREAD

**Issue by anonym-HPI** [hpi-sam/digital-fuesim-manv#364]
When I am using a Laptop with a touch pad I can zoom into the whole webpage (being in trainer mode), having scroll bars, this is really annoying and it is difficult to zoom out (if you are on the map you are zooming in and out on the map, but not webpage anymore, so you can e.g. use the scroll bars to get to the part outside the map and zoom out).

**Comment by ClFeSc** [comment]
I'm not sure this is what @anonym-HPI noticed, but when I made the tests on the slow devices on one of them I zoomed into the webpage instead of just the map (like with using the magnifier or whatever it's called).

**Comment by Dassderdie** [comment]
Not able to reproduce this. In the worst case, you can just reload the webpage.
