### ISSUE TITLE
Hospital system

### ISSUE THREAD

**Issue by Dassderdie** [hpi-sam/digital-fuesim-manv#378]
* Add/edit hospitals
* Transfer to hospitals
* Statistics @Dassderdie  #370 

Edit:
previous proposal (that was in the pull request):
-   make transferpoints have a type (normal, hospital) and an event when a vehicle arrives at them
    -   advantage: hospital benefit from changes on transferpoints and features (e.g. can be seen in transfer overview)
    -   disadvantage: how to implement capacities (overall and for red, yellow, what about special treatment patients, right now we seem only having a free text with description)?
    -   events: normal having no event (right now), hospitals having event: "patient arrived and gets deleted + TODO: what to do with vehicle? Send it back to where it came with like 30 min. delay (for offloading, refilling, ...)?"
-   make transferpoints only available for vehicles (not sending personnel to hospital)
-   pause patients on the way to a hospital
-   let trainers create hospitals
-   statistics distinguish between normal transferpoints and hospitals

**Comment by Dassderdie** [comment]
@anonym-HPI I think an issue is a better place to discuss this instead of pull request #381 

> -   make transferpoints have a type (normal, hospital) and an event when a vehicle arrives at them
>     -   advantage: hospital benefit from changes on transferpoints and features (e.g. can be seen in transfer overview)
>     -   disadvantage: how to implement capacities (overall and for red, yellow, what about special treatment patients, right now we seem only having a free text with description)?

I think it would be better to separate `TransferPoints` and `Hospitals` (Hospitals don't have a position and no internal name). Maybe introduce a new `TransferTarget` class so that the transfer behavior is better encapsulated (composition pattern).

I mostly start with a bit of code duplication and refactor it after I have a clear idea of which parts of the code can be encapsulated.

>     -   events: normal having no event (right now), hospitals having event: "patient arrived and gets deleted + TODO: what to do with vehicle? Send it back to where it came with like 30 min. delay (for offloading, refilling, ...)?"

This would be done in the `ExerciseTickActionReducer` when refreshing the transfers. For now, it would be enough to delete patients and vehicles when they arrive.

> -   make transferpoints only available for vehicles (not sending personnel to hospital)

Maybe even only full vehicles (else we could end up with personnel without a vehicle because it got deleted -> currently an invalid state).
It should be relatively straight forward with our current architecture to add such an validator (`TransferPointFeatureManager.onFeatureDrop` and `ChooseTransferTargetPopupComponent`)
 
> -   pause patients on the way to a hospital

I guess `patientTick()` in `backend\src\exercise\patient-ticking.ts` would be the correct place for that. Either pause the patients when they are in a vehicle or if they are in a vehicle that is on the way to a hospital. What do you think @hpistudent72 (because this is probably part of your bachelor's thesis)?

> -   let trainers create hospitals

As well as edit and delete. Probably via another modal?

> -   statistics distinguish between normal transferpoints and hospitals

I don't have any statistics for normal TransferPoints. I would say the statistics are out of scope for this issue, I can add them with ease after the hospital functionality is merged.

You also had some thoughts about capacities (Please use GitHub for this as a single channel of communication):

> Zur Kapazität, dass könnte man vllt verbinden mit "Transferverbindungen haben eine sichtbare und editierbare Kapazität" und der Unterschied bei Krankenhäusern, ist dass diese nicht nach dem erreichen eines Fahrzeuges sinkt.
> Man könnte also die Reduktion der Kapazität beim normalen Transferpoint über den Vorschlag mit dem "arrival" event einführen.
> Man müsste, wenn ein Fahrzeug umdisponiert werden gucken, dass die Kapazitäten aktualisiert werden und überlegen, ob Trainer die Kapazität überschreiten dürfen (beim umdisponieren)

I would not include such functionality yet -> we have only three weeks until Ahrweiler.

**Comment by Dassderdie** [comment]
@christianzoellner

**Comment by christianzoellner** [comment]
> @anonym-HPI I think an issue is a better place to discuss this instead of pull request #381

I would also prefer to discuss concepts in an issue first.

---

> I think it would be better to separate `TransferPoints` and `Hospitals` (Hospitals don't have a position and no internal name). Maybe introduce a new `TransferTarget` class so that the transfer behavior is better encapsulated (composition pattern).

That sound indeed like a perfect usecase for inheritance. 
It suffices that hospitals can be added as `TransferTarget` when editing a transfer point. Besides that there doesn't need to be much overlap with the Transfer Point mechanic.

**Comment by christianzoellner** [comment]
@Dassderdie I am looking for the list of requirements that your comment seems to be commenting on. Where was ist it? Have they been in the PR and then deleted again, or am I looking at the wrong place altogether?

@anonym-HPI we should discuss the requirements and basic concept early on.

**Comment by Dassderdie** [comment]
> @Dassderdie I am looking for the list of requirements that your comment seems to be commenting on. Where was ist it? Have they been in the PR and then deleted again, or am I looking at the wrong place altogether?

Look at the changed files in the PR. I haven't encountered this place for a design proposal  before myself XD

> @anonym-HPI we should discuss the requirements and basic concept early on

Agreed. Either I or @ClFeSc should be present in this meeting as well for the technical side of things.

**Comment by christianzoellner** [comment]
ufff... that information is well hidden indeed, and it's made hard to comment on. :-)

@anonym-HPI Do you prefer a meeting at HPI or should I respond to your notes in this issue?

**Comment by anonym-HPI** [comment]
Current design getting implemented:
- hospitals can be created via a menu in the trainerbar
- hospitals have a name and a duration for the transport (duration not changing between `transferPoints`)
- hospitals can be connected via the `transferPoint` popup
- if a vehicle is sent to a hospital the vehicle and everything connected to it (personnel, material and loaded patients) will be deleted
- before the patient is deleted the patient info is saved to a `hospitalPatient`
- this patient info includes everything that is visible when opening a patient popup, it includes also the time the patient was sent to the hospital and the arrival time at the hospital (the way to the hospital is not simulated)
  - this patient info can be used for statistics/analytics (not included in this issue)

**Comment by christianzoellner** [comment]
@anonym-HPI in order to be able to access patient-history of a `hospitalPatient`, wouldn't it be easier to simply copy the patient object from a list of "active" patients to another  list of "hospitalized"/"transported" patients, that is not considered during the update `Ticks`? 
That way, any previous actions referencing the `patient` object are still valid and can be attributes.

(cc @Dassderdie)

**Comment by anonym-HPI** [comment]
> 

That is actually the way I am implementing it, I create a `hospitalPatient` that just copies information from a `patient `and then the original patient is deleted.
Do you mean `healthStates`? These are copied. Right now the `hospitalPatient` saves the original `patient.id` under `patientId` (so references that used the Id can be used, as well).
