### ISSUE TITLE
Double clicking Join button sends event twice

### ISSUE THREAD

**Issue by ClFeSc** [hpi-sam/digital-fuesim-manv#380]
When entering a name, you can double-click (e.g. by double-tapping enter) the join button which sends two `joinExercise` events and adds the client twice to the state.

I'd imagine this could be fixed both in the frontend and the backend:
* The frontend should not allow multiple clicks on this button.
* The backend should not allow multiple clients from one socket. -> Fixed in #388

**Comment by Dassderdie** [comment]
This is  a wontfix for the frontend (cost/benefit)
