### ISSUE TITLE
Performance on some devices

### ISSUE THREAD

**Issue by ClFeSc** [hpi-sam/digital-fuesim-manv#383]
I tried to be a participant on some old devices I've got lying around.

1. [Vodafone Smart Tab 4](https://www.hifitest.de/test/ausstattungsliste/tablets/vodafone-smart-tab-4-53813) (although I'm not sure this is the exact model I've got): Device is no longer supported since an eternity, so it's stuck on Android 4.2.2 with Chrome 47. It won't even render the landing page and does the same for other websites. I could not install any non-Chromium-based web browser due to the apps being incompatible with the device.
2. [Samsung Tab A](https://www.gsmchoice.com/de/katalog/samsung/galaxytaba9.7/): Still somewhat supported, so it runs Chrome 101 (latest as of writing this) on Android 7.1.1. It runs the landing page just fine, and the map is somewhat usable until there is an object visible, like a vehicle. At least after emptying the vehicle the drag performance becomes unusable. The same happens in Firefox 100 (also the latest as of writing this), although it supports I'd say up to one vehicle, after this it becomes unusable. This is however a known issue with this device and also happens for other map-based applications like Google Maps.
3. [Samsung Galaxy A3 2016](https://www.inside-digital.de/handys/samsung-galaxy-a3-2016): Not really supported anymore. Using Chrome 73 on Android 7.0 it becomes unusable the moment you have some object on the map. After updating Chrome to version 101 no change in behavior could be observed. I didn't want to stress the phone anymore, so I didn't try to install Firefox. It's also a phone with quite a small screen so I doubt anyone would like to use it for the program anyway, I just wanted to test it with this as well.

On my current phone (a [Honor View20](https://www.gsmarena.com/honor_view_20-9468.php) running Android 10) Chrome 101 has some problems with multiple vehicles and patients. Firefox 100 handles it way better, I'd even say it could be used for training in this setup.

What all devices did was disconnect from the WebSocket connection once you leave the tab (e.g. by locking the screen or changing the active app). Also, especially on phones, the small screen makes it difficult to navigate without accidentally moving something around.

I also tested it with a VM restricted to ~1 GiB of RAM with ~1 GiB swap space and one logical core running Ubuntu 20.04.4 LTS 64 Bit. Using Firefox 99 it's a bit laggy but I'd say at least for small exercises still usable. Edit: Note that this may be related to missing GPU acceleration in the VM.

All tests were run on an exercise on the deployed dev version of the program.

**Comment by Dassderdie** [comment]
Thx for the information :)
