### ISSUE TITLE
Immutability of action in reducer could lead to problems

### ISSUE THREAD

**Issue by Dassderdie** [hpi-sam/digital-fuesim-manv#390]
Currently, a reducer gets a mutable `ExerciseState` (immer draft) and an immutable `Action` that should be applied.

The following would produce a runtime error (not just semantically, but an actual error because of `Object.freeze`), but no type error:

```ts
        reducer: (draftState, { mapImage }) => {
            draftState.mapImages[mapImage.id] = mapImage;
            draftState.mapImages[mapImage.id].position.x = 0;
            return draftState;
        },
```

The underlying problem is described [here](https://github.com/microsoft/TypeScript/issues/13347).

I see two possibilities:

1. Document this somewhere 
2. Make the action mutable too (either trivially by deep cloning the action or by adding the action to the draft (like `{ draftState, draftAction }` )). This would hurt performance a bit, I guess? Though, if you only need to read from a huge action (e.g., the treatment stuff in the tick), you could still use [original()](https://immerjs.github.io/immer/original).

The same problem could occur when assigning a model that was created via our `Model.create()` method because they are also immutable (which is enforced via `Object.freeze()`).

**Comment by ClFeSc** [comment]
> Currently, a reducer gets a mutable `ExerciseState` (immer draft) and an immutable `Action` that should be applied.
> 
> The following would produce a runtime error (not semantically, but an actual error because of `Object.freeze`), but no type error:
> 
> ```ts
>         reducer: (draftState, { mapImage }) => {
>             draftState.mapImages[mapImage.id] = mapImage;
>             draftState.mapImages[mapImage.id].position.x = 0;
>             return draftState;
>         },
> ```

I'd expect a type error...

> The underlying problem is described [here](https://github.com/microsoft/TypeScript/issues/13347).

...but no type error. Bummer!

What can we do?

> I see two possibilities:
> 
>     1. Document this somewhere

Definitely!

>     2. Make the action mutable too (either trivially by deep cloning the action or by adding the action to the draft (like `{ draftState, draftAction }` )). This would hurt performance a bit, I guess? Though, if you only need to read from a huge action (e.g., the treatment stuff in the tick), you could still use [original()](https://immerjs.github.io/immer/original).

Hm, I'm not sure I like this idea. What about only deep cloning the parts of the action that are actually used in such a way, e.g. by using our `cloneDeepMutable`? We even use this style already when calculating treatments (e.g. in `AddPatientAction`).

> The same problem could occur when assigning a model that was created via our `Model.create()` method because they are also immutable (which is enforced via `Object.freeze()`).
