### ISSUE TITLE
Starting position for additional trainer

### ISSUE THREAD

**Issue by christianzoellner** [hpi-sam/digital-fuesim-manv#394]
### Problem:
As a co-trainer who joins in creating or managing an exercise, I don't want o look for the exercise in the world first.

### Solution:
Assign trainers a starting position for their view based on the other trainers and/or exercise elements.

### Implementation Ideas:
* Center view on the midpoint of all exercise elements.
* Use bounding box of all viewports as view area (advantageous because viewports are visible on all zoom levels).
* Give trainers a "set this as default view" button to define the starting points.

**Comment by anonym-HPI** [comment]
Right now this is already manually possible, but not intuitive and cumbersome (the first trainer can create a viewport somewhere and name it like "trainer start position" and new trainers can select it in the participant overview and unselect themselves afterwards.

**Comment by christianzoellner** [comment]
> Right now this is already manually possible, but not intuitive and cumbersome (the first trainer can create a viewport somewhere and name it like "trainer start position" and new trainers can select it in the participant overview and unselect themselves afterwards.

A worksround that requires a lot of knowledge of the trainer mechanics. I would not recommend to put that in a user manual. :-)
