### ISSUE TITLE
Problems with transfer point deletion

### ISSUE THREAD

**Issue by ClFeSc** [hpi-sam/digital-fuesim-manv#404]
There are some problems regarding transfer points that can crash the backend (in dev, in production it's catched):

* When a vehicle arrives at a transfer point that has been deleted while it was in transfer it crashes.
* When a transfer point with a connection to another transfer point gets deleted it also crashes.

**Comment by Dassderdie** [comment]
> Another problem: I can alarm a group to a deleted transfer point when it's the previously selected target.
> 
> I wanted to display invalid transferPoints in app-transfer-point-name with text-danger -> there would be at least a visual indicator for it. (https://github.com/hpi-sam/digital-fuesim-manv/issues/358) We could also check whether the transferPoint exists before alarming the group (getStateSnapshot).

#384
