### ISSUE TITLE
Refactor Send Alarm Groups into one action

### ISSUE THREAD

**Issue by hpistudent72** [hpi-sam/digital-fuesim-manv#406]
The code in question is in `frontend\src\app\pages\exercises\exercise\shared\emergency-operations-center\send-alarm-group-interface\send-alarm-group-interface.component.ts` - `sendAlarmGroup`.

Currently, to alarm the `alarmGroup`, we are not adding a group of vehicles but all vehicles one by one. In addition, each vehicle is, after creation, separately added to the transfer.
This results in 2 actions per vehicle in an `alarmGroup` (alarmGroups can have >10 vehicles).

Why are we doing it like this?

Reducer cannot handle non-deterministic functions like `Date.now()`, `Math.random()` and **`uuid()`**.
If the reducer created a vehicle from a VehicleTemplate, it would need to call `uuid()` to get the `id`, which would break the synchronization. Therefore the vehicle is sent via the action. 

This issue doesn't try to remove the underlying limitations but instead tries to improve the current workaround. All actions for sending an alarmGroup should be merged into a single (big) one.

#### Implementation

* In `shared\src\store\action-reducers\alarm-group.ts`, add an `SendAlarmGroupAction` like this:
```ts
export class SendAlarmGroupVehicleAction implements Action {
    @IsString()
    public readonly type = '[AlarmGroup] Send AlarmGroup';
   
    targetTransferPointId: UUID;

    @IsArray()
    @ValidateNested()
    @Type(() => AddVehicleAction)
    public vehiclesToAdd: AddVehicleAction[];   
}
```

In the corresponding actionReducer (same file, below), you can then apply the action via  `draftState = applyAction(draftState, addVehicleAction);`. The same can be done with the `Add to transfer` action to add the vehicle to the transfer.

The respective Log message could also be created in the same reducer (requires adding the `alarmGroupId` and `clientId`). But I'm not sure whether this would be good...

**Comment by lukasrad02** [comment]
Refactoring took place in #910.
