### ISSUE TITLE
Port over fixes/features from experimental to dev

### ISSUE THREAD

**Issue by ClFeSc** [hpi-sam/digital-fuesim-manv#435]
This includes:

- [ ] Prevent crashing on http requests (#430)
- [x] `PatientCategory.name` is incorrectly validated as `@IsString()` (https://github.com/hpi-sam/digital-fuesim-manv/commit/2c091a9297da94c32d37b7bddb5269de3083d38b)
- [x] The import payload size is pretty limited (https://github.com/hpi-sam/digital-fuesim-manv/commit/f10b1543c571159ee77f8c8cb4e7495a06c3c00c)
- [x] Alarm Group Vehicle names are not applied to personnel and material (https://github.com/hpi-sam/digital-fuesim-manv/commit/c759c3bfa807e650bf398bde6a3b0e9ad6ab489b)

**Comment by Dassderdie** [comment]
For the only open task, there is a separate issue -> close?
