### ISSUE TITLE
Increase import/upload size and editable via ENV

### ISSUE THREAD

**Issue by anonym-HPI** [hpi-sam/digital-fuesim-manv#464]
Right now, the upload size is limited to 1mb
via http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size (when using docker)
and to 200mb in backend\src\exercise\http-server.ts (without docker, as no nginx)

at least setting it to 200MB in nginx and better make it editable via ENV

checking: the different writing, in nginx it is `200M` and in http-server.ts `200mb` - checking if both could use `MB` or so

**Comment by ClFeSc** [comment]
@anonym-HPI Any progress on this? It would be quite important for a usable experience.
