### ISSUE TITLE
Set `participantId` in the constructor of an `ExerciseState`

### ISSUE THREAD

**Issue by Dassderdie** [hpi-sam/digital-fuesim-manv#467]
...instead of using an action.

**Comment by ClFeSc** [comment]
What should happen on import? Should we continue to use an action, or should we use something else (what would that be)?

**Comment by Dassderdie** [comment]
We mutate the exercise without an action. The initialState should already have the participantId

**Comment by ClFeSc** [comment]
Ah, right. We have to set it to the `initialState`, not just the `currentState`.
