### ISSUE TITLE
Do not create WebSocket connection on landing page

### ISSUE THREAD

**Issue by Dassderdie** [hpi-sam/digital-fuesim-manv#470]
Currently, a WebSocket connection to the server is always created when a client is on the website.
Instead, it should only be initiated when joining an exercise and stopped when leaving it.

This should probably be done by treating the `presentExerciseHelper` like the `TimeTravelHelper` in  #447 (only create it when joining an exercise and destroy it when leaving).

**Comment by christianzoellner** [comment]
Would avoid ugly timeouts on landing page. All for it!
