### ISSUE TITLE
Show personnel type

### ISSUE THREAD

**Issue by Dassderdie** [hpi-sam/digital-fuesim-manv#487]
Currently, nobody knows which personnel-image represents which personnel type.

**Comment by Dassderdie** [comment]
Ideas:
* Write the abbreviation (`NotSan`, `NA`, ..) below the personnel
* Add the abbreviation (`NotSan`, `NA`, ..) diretly to the personnel image
* Add a popup that shows the type when clicking on the personnel

@christianzoellner This would probably be neat for Wednesday. Do you have any other proposals/preferences?

**Comment by christianzoellner** [comment]
@Dassderdie thanks for bringing this up.

What I would like: 
* Type of the personnel is more important than the vehicle code and needs to be in text form to be well understood by everyone. It should be under or in front of the icon (tough I doubt that the latter looks good). 
* Names should have similar length: So either..
  * ...long abbreviations: `Notarzt`, `Arzt` (if you have that), `NotSan`, `RettSan`, `Sanitäter`, `GruFü` 
  * ...OR short abbreviation: `NA`, `A`, `NFS`, `RS`, `San`, `GF`
* The vehicle assignment is not as important, but should be reachable. You might...
  *  ...put it in a details popup. You might also include information where the vehicle is (which would be cool).
  * ...show it under the type text in slightly smaller writing as a subtile. Zooming in for details can be consisdered a feature.

Can you work with that?
