### ISSUE TITLE
Patient Statistics (or similar feature) should be availabe during exercise creation

### ISSUE THREAD

**Issue by christianzoellner** [hpi-sam/digital-fuesim-manv#497]
Currently, when I am creating an exercise (i.e. placing patients and viewpoints at time = 0:00), I have no way to see aggregated how many patients there are per viewport. This would be really helpful.

Maybe the statistics can be made to also show the current value?

![image](https://user-images.githubusercontent.com/4678160/181264040-5148e5ab-aaf6-4062-86b9-a86d5aed7ea6.png)

**Comment by Dassderdie** [comment]
Potentially fixed by #449

**Comment by christianzoellner** [comment]
> Potentially fixed by #449

@Dassderdie can I test this somewhere?

**Comment by Dassderdie** [comment]
> > Potentially fixed by #449
> 
> @Dassderdie can I test this somewhere?

In theory on the live server since a few hours ago. In practice this still doesn't seem to be working -> I'm investigating

**Comment by christianzoellner** [comment]
@Dassderdie please mention me again when I should check

**Comment by Dassderdie** [comment]
@christianzoellner I investigated and came to the conclusion that it is not yet solved. I'll make a pull request during the weekend.
