### ISSUE TITLE
Use specific version of state in action migrations

### ISSUE THREAD

**Issue by ClFeSc** [hpi-sam/digital-fuesim-manv#524]
Action migrations currently get the most up-to-date state whereas it would be much better to receive the state migrated to the version of the action migration. E.g. for a migration from version 4 to 5, the action migration would receive the initial state migrated to version 5, regardless of the current latest possible version.

**Comment by christianzoellner** [comment]
Assignes @Dassderdie for detailed triage.

**Comment by Dassderdie** [comment]
Seems to be completely contained in `backend\src\database\state-migrations\migrations.ts` -> Good first issue

**Comment by ClFeSc** [comment]
I already have a solution, I just have to push it, will do this probably today.
