### ISSUE TITLE
Patients added to imported exercices are not visible

### ISSUE THREAD

**Issue by lukasrad02** [hpi-sam/digital-fuesim-manv#555]
Steps to reproduce:
1. Import an exercise from the [test scenarios](https://github.com/hpi-sam/digital-fuesim-manv_test-scenarios)
2. Add a patient to the map

While patients created in the imported exercise are visible, new patients only show their pretriage indicator but not the patient image itself.

The following image shows one patient from the imported exercise (green indicator, lower left corner) and one new patient (white indicator, upper right corner):
![image](https://user-images.githubusercontent.com/49586507/194913343-6005067d-24e8-4cf4-8873-29f97fa918d8.png)

This bug only occurs for exercises with state version 2 and 4 but not for those with state version 9 or 10 (most recent version as of creating this issue), so it might be related to migrations between.

**Comment by ClFeSc** [comment]
Yes, this should be the reason.

**Comment by ClFeSc** [comment]
I think we'd have to write a new migration that changes every occurrence of `male-patient.svg` to `patient.svg`.

**Comment by ClFeSc** [comment]
The problem with the migration is that both the `patientCategories` entry (that got migrated) and the `patientTemplates` entry (that hasn't been migrated) have an image.
