### ISSUE TITLE
Upgrade to node 18

### ISSUE THREAD

**Issue by Dassderdie** [hpi-sam/digital-fuesim-manv#578]
Node 18 is now LTS and I think all our packages have a version that supports it.

**Comment by Greenscreen23** [comment]
We are going to do this on the cypress branch, as cypress seems to crash on node 16. This will also ensure that the new node version is properly tested :)

**Comment by Dassderdie** [comment]
> We are going to do this on the cypress branch, as cypress seems to crash on node 16. This will also ensure that the new node version is properly tested :)

Then don't forget to
* Update the README
* Update the `engines.node` property in all four `package.json`s
* Update the Pipeline versions
* Update the docker image

**Comment by Greenscreen23** [comment]
> > We are going to do this on the cypress branch, as cypress seems to crash on node 16. This will also ensure that the new node version is properly tested :)
> 
> Then don't forget to
> 
>     * Update the README
> 
>     * Update the `engines.node` property in all four `package.json`s
> 
>     * Update the Pipeline versions
> 
>     * Update the docker image

All done :)
