### ISSUE TITLE
Personnel is automatically assigned to patients and treats them

### ISSUE THREAD

**Issue by Nils1729** [hpi-sam/digital-fuesim-manv#598]
When personnel and patients are in the same autonomous region, the personnel do triage and they patients and personnel are automatically matched such that the patients are being treated.

For this, we extend the existing tick action,

Requirement: M3b

**Comment by Nils1729** [comment]
Blocked by #597

**Comment by Nils1729** [comment]
I suggest using this issue as a starting point to lay the foundation for sophisticated region behavior.
The changes themselves will likely hook into `calculate-treatments.ts`.

**Comment by christianzoellner** [comment]
@Nils1729 before you start implementing this, let's meet to discuss the _strategy_ that decides in which order personnel triage and treat which patient. Shouldn't be too difficult to find something reasonably realistic.

**Comment by christianzoellner** [comment]
(assuming that your comments mean that you are responsible for this issue @Nils1729)

**Comment by Greenscreen23** [comment]
We're currently discussing how changes caused by the simulation should propagate to the clients. The *strategy* should be something that can be changed reasonably late into the process.

**Comment by Greenscreen23** [comment]
We split this issue in two, the first to be resolved of which is #638
