### ISSUE TITLE
Update Image for Johanniter Akademie NRW, Campus Münster der Johanniter-Unfall-Hilfe e.V. (JUH)

### ISSUE THREAD

**Issue by Nils1729** [hpi-sam/digital-fuesim-manv#600]
Use the image from the requirements document

**Comment by Nils1729** [comment]
The images are not part of this repo but instead fetched from <https://www13.hpi.uni-potsdam.de/fileadmin/user_upload/fachgebiete/giese/Bachelorprojekte/2021/>. If we do not change that, we need to ask the supervisors to upload the new file.

**Comment by christianzoellner** [comment]
@Nils1729  here ist the link the the newly uploaded image:

`https://www13.hpi.uni-potsdam.de/fileadmin/user_upload/fachgebiete/giese/Bachelorprojekte/2022/johanniter-akademie-nrw-logo.png`
