### ISSUE TITLE
Use opaque fill style for simulated regions

### ISSUE THREAD

**Issue by Nils1729** [hpi-sam/digital-fuesim-manv#603]
This requires the Geometry to be changed from `LineString` to `Polygon`.

Consequently, we need to touch a lot of the OpenLayers wrappers (`ElementManager`, `FeatureManager`, ...)

**Comment by Dassderdie** [comment]
The current implementation for the viewports uses `LineString`s. This does not only mean that there is no fill-color available, but you are also only able to drop elements on the border of your `simulatedRegions`, and clicks are only registered on the borders too.

The best solution for this would be to refactor the `viewports` and `simulatedRegions` from `LineString` to `Polygon`.
`viewports` would just be `Polygons` without the `fill`-attribute.

You can see a rough prototypical sketch of the necessary refactoring in e59939cb623799cf90dc1417f4b88a7f74e61f78

* Most utilities must support `Point`, `LineString` and `Polygon`
* In the `ModifyHelper`. `viewport-modify` and `translate-interaction` the `Polygon` should just be able to replace the `LineString`

**Comment by Greenscreen23** [comment]
> The current implementation for the viewports uses LineStrings. This does not only mean that there is no fill-color available, but you are also only able to drop elements on the border of your simulatedRegions, and clicks are only registered on the borders too.

I think this is a huge deal for us, so we will probably have to do this at some point. I will take a look at this, but we'll merge this after #604

**Comment by Greenscreen23** [comment]
> You can see a rough prototypical sketch of the necessary refactoring in https://github.com/hpi-sam/digital-fuesim-manv/commit/e59939cb623799cf90dc1417f4b88a7f74e61f78

What was your reasoning for removing catering and transfer lines? Just for the ease of it, or is there a problem that some layers can't be line layers while others are vector layers that I'm missing?

**Comment by Dassderdie** [comment]
> > You can see a rough prototypical sketch of the necessary refactoring in https://github.com/hpi-sam/digital-fuesim-manv/commit/e59939cb623799cf90dc1417f4b88a7f74e61f78
> 
> What was your reasoning for removing catering and transfer lines? Just for the ease of it, or is there a problem that some layers can't be line layers while others are vector layers that I'm missing?

Just for the ease of it. I wanted to see whether the Polygon without a fill would have the correct hitbox.
