### ISSUE TITLE
Close popups with ESC

### ISSUE THREAD

**Issue by Nils1729** [hpi-sam/digital-fuesim-manv#605]
For ease of development, it would be nice if all popups on the map and elsewhere could be closed by pressing ESCAPE.

**Comment by lukasrad02** [comment]
To implement this feature, we could add an interaction like in [this SO post](https://stackoverflow.com/a/69392146) to the OL map manager (`frontend/src/app/pages/exercises/exercise/shared/exercise-map/utility/ol-map-manager.ts`). But this catches the keyboard events only if no textbox in the currently open popup has keyboard focus (although the `Escape` key has no effect on the textbox).

So if we'd like to be able to use the Escape key always, we have to add events handlers to all input elements in the popups, which would be a lot of work. We've got to decide what exactly is the desired behavior.

**Comment by Dassderdie** [comment]
Try this:

in `ol-map-manager.ts` at the end of `registerPopupTriggers()`:

```ts
        this.openLayersContainer.addEventListener('keydown', (event) => {
            if ((event as KeyboardEvent).key === 'Escape') {
                this.changePopup$.next(undefined);
            }
        });
```

I don't think we need OpenLayers here and can just use the HTML events.
I'm not sure whether `event.preventDefault()` and/or `event.stopPropagation()` would be good here...

**Comment by Dassderdie** [comment]
Be aware that this doesn't save the last input if you closed the modal too soon (600ms) after the last keypress in an input element.
This is due to the self-made `saveOnTyping`-directive. I will provide a fix for that.

**Comment by lukasrad02** [comment]
> Try this:
> 
> in `ol-map-manager.ts` at the end of `registerPopupTriggers()`:

Thank you for the hint. I've only tried registering events on `this.olMap`, which does not provide keyboard events.

**Comment by lukasrad02** [comment]
> I'm not sure whether `event.preventDefault()` and/or `event.stopPropagation()` would be good here...

I'm not aware of any default behavior of the escape key and didn't notice any differences with or without `preventDefault()`.
The same applies to `stopPropagation()`, there are no other custom features using the escape key.

So I would not include any of these. But if you generally include one of these methods in this project, I would follow your convention.

**Comment by Dassderdie** [comment]
> I'm not aware of any default behavior of the escape key and didn't notice any differences with or without `preventDefault()`. The same applies to `stopPropagation()`, there are no other custom features using the escape key.
>
> So I would not include any of these. But if you generally include one of these methods in this project, I would follow your convention.

👍 We don't have such a convention (yet). This was just a general consideration about how this should behave, but YAGNI is valid here too.

**Comment by Dassderdie** [comment]
> Be aware that this doesn't save the last input if you closed the modal too soon (600ms) after the last keypress in an input element. This is due to the self-made `saveOnTyping`-directive. I will provide a fix for that.

Try this in `frontend\src\app\shared\directives\app-save-on-typing.directive.ts`:


```ts
export class AppSaveOnTypingDirective implements OnDestroy {
    destroy$ = new Subject<void>();
    @Output() readonly appSaveOnTyping: EventEmitter<any> = new EventEmitter();

    private lastInputValue?: any;
    private lastInputValueWasValid = false;
    private lastSubmittedValue?: any;

    constructor(ngModel: NgModel) {
        ngModel.update
            .pipe(
                tap((value) => {
                    this.lastInputValue = value;
                    this.lastInputValueWasValid = ngModel.valid === true;
                }),
                // Keeping a key (like backspace) pressed for a more than a certain threshold will result in many key presses
                // The debounceTime should be above that threshold to not register the initial keypress as the first update
                debounceTime(600),
                filter(() => ngModel.valid === true),
                takeUntil(this.destroy$)
            )
            .subscribe((value) => {
                if (this.lastSubmittedValue === value) {
                    // We don't want to emit the same value twice in a row
                    return;
                }
                this.lastSubmittedValue = value;
                this.appSaveOnTyping.next(value);
            });
    }

    ngOnDestroy() {
        if (
            this.lastInputValueWasValid &&
            this.lastInputValue !== this.lastSubmittedValue
        ) {
            // The last input value was not submitted yet
            // We want to emit this last value before the appSaveOnTyping gets
            // unsubscribed from during the destruction of the parent component
            this.appSaveOnTyping.next(this.lastInputValue);
        }
        this.destroy$.next();
    }
}
```
