### ISSUE TITLE
Features disappear from the map in imported exercises

### ISSUE THREAD

**Issue by lukasrad02** [hpi-sam/digital-fuesim-manv#621]
After importing the exercise https://github.com/hpi-sam/digital-fuesim-manv_test-scenarios/blob/main/exercise-state-2022-05-31-small-demo.json elements disappear from the map after performing an action.

For example, when you drop a patient onto a vehicle an then move the map, all other patients, material, and the personnel disappears:

https://user-images.githubusercontent.com/49586507/214319673-d3a39fd5-315b-41b7-8b8f-4ec594fde8e4.mp4

This issue has first been detected during the review of #607, but as it also appears at the current state of the `dev` as well as `main` branch.

The problem seems to be in the frontend only, as there is no websocket communication despite the action for the patient dropped onto the vehicle. Additionally, the browser console shows several type errors:

```
[...]
ERROR TypeError: can't access property "vehicleTemplates", exercise is undefined
ERROR TypeError: can't access property "mapImageTemplates", exercise is undefined
ERROR TypeError: can't access property "clients", exercise is undefined
ERROR TypeError: can't access property "currentStatus", exercise is undefined
ERROR TypeError: can't access property "configuration", exercise is undefined
ERROR TypeError: can't access property "transferPoints", exercise is undefined
[...]
```

**Comment by lukasrad02** [comment]
After some further investigation, I've found out that

- the issue applies to other exercises from the test scenarios repo, too
- the bug does only occur if the first action after importing the exercise is the load vehicle action. If any feature is moved/added/removed before, there is no unintended behavior

**Comment by lukasrad02** [comment]
Even further investigation by our team showed that the issue is not related to imported exercises. The issue occurs if the first action after joining the exercise is a load vehicle action.

Since one usually has to add vehicles and patients after joining the exercise before one can load a vehicle, the bug only showed up in imported exercises.

Therefore, to reproduce the issue, perform the following steps:

1. Create a new exercise and join as trainer
2. Add a vehicle that can contain patients (e.g. RTW) and two patients
3. Refresh the page in your browser or open a second window/tab and join the exercise
4. Drop one of the two patients onto the vehicle without releasing the patient on their way
5. Move the map slightly and observe the other patient disappearing

**Comment by Dassderdie** [comment]
> Even further investigation by our team showed that the issue is not related to imported exercises. The issue occurs if the first action after joining the exercise is a load vehicle action.
> 
> Since one usually has to add vehicles and patients after joining the exercise before one can load a vehicle, the bug only showed up in imported exercises.
> 
> Therefore, to reproduce the issue, perform the following steps:
> 
> 1. Create a new exercise and join as trainer
> 2. Add a vehicle that can contain patients (e.g. RTW) and two patients
> 3. Refresh the page in your browser or open a second window/tab and join the exercise
> 4. Drop one of the two patients onto the vehicle without releasing the patient on their way
> 5. Move the map slightly and observe the other patient disappearing

This sounds like I could have caused it with #564 😟 
I'll have a look at it this evening if you haven't figured it already out until then...
