### ISSUE TITLE
Display counters for patients, personnel and material in a simulated region

### ISSUE THREAD

**Issue by Greenscreen23** [hpi-sam/digital-fuesim-manv#641]
Trainers should be able to view which entities are inside of a simulated region.

**Comment by benn02** [comment]
Currently they exist sort of but they need to be improved (it needs to look good :) )

**Comment by Nils1729** [comment]
Inspiration can be taken from [this commit](https://github.com/hpi-sam/digital-fuesim-manv/pull/664/commits/0c94f05a986ad24117b217c35bb67cf9bc601480).

**Comment by benn02** [comment]
Obsolete since #703
