### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by Greenscreen23** [hpi-sam/digital-fuesim-manv#646]

**Comment by Greenscreen23** [comment]
I'm taking a look how we might add cypress tests.

**Comment by Dassderdie** [comment]
> I'm taking a look how we might add cypress tests.

See #525

**Comment by Greenscreen23** [comment]
We have noticed that cypress tests can take quite a while to execute. We are therefore thinking about only running those tests for commits to dev. We also decided against using visual tests (screenshots), as these will result in a lot of false positives.
