### ISSUE TITLE
Enforce connection of vehicle to material an personnel with regard to simulated regions

### ISSUE THREAD

**Issue by Nils1729** [hpi-sam/digital-fuesim-manv#660]
When vehicles are being moved to simulated regions, the associated personnel and materials are currently left behind. Materials and Personnel should be moved to the simulated region too. This preferably only affects those elements that are not in the vehicle as the others should stay in the vehicle which itself is moved to the simulated region.

**Comment by christianzoellner** [comment]
Alternatively, you could reject moves of emtpy vehicles or out-of-vehicel-personnel to simulated regions. Might be less complicated.
