### ISSUE TITLE
Feature request: drop patients, vehicles and personnel to simulated regions when dragging from the trainer map editor

### ISSUE THREAD

**Issue by Greenscreen23** [hpi-sam/digital-fuesim-manv#668]
Currently, we can drop patients, vehicles and personnel to simulated regions when dragging them on the map. However: If we drag them from the trainer map editor, they don't enter the region. I don't think this is intended.

**Comment by benn02** [comment]
I would not consider it a Feature, not a Fix since this was never intended to work this way previously.

**Comment by Greenscreen23** [comment]
Then its a feature request, as we need it for cypress testing :)
