### ISSUE TITLE
Handle failed migrations in the backend

### ISSUE THREAD

**Issue by benn02** [hpi-sam/digital-fuesim-manv#709]
Migrations in the backend currently can fail due to expected reason like minor version changes. This should not cause the backend to crash. Instead, the User should be informed, and the exercise should be deleted, and the migration process should continue. Alternatively, the user is informed that the migration only partially worked, and some actions are not repeated if they throw an error.

**Comment by benn02** [comment]
> 
> If the server fails after running the migrations on the database, this usually means that a migration was incorrect and should be fixed. Therefore, it was intended behavior for the server to fail instead of running with incorrect migrations or an invalid state. Though, before doing this, one should probably test this database in a staging environment.

This is not the case since, as stated in the issue, there are some migrations that are expected to fail because of changes in the action reducers that make previously legal actions illegal without the existence of an appropriate replacement. Those actions can't be applied, so the server crashes. Instead it should not execute those actions or delete the exercise.

**Comment by ClFeSc** [comment]
I don't think deleting exercises that fail the migration should be deleted. This would be a very bad time when you as a user want to use the exercise again, but it's suddenly not there anymore, and hard to impossible to recover.

Also, what changes do you have in mind that would have a failure as an expected outcome?

**Comment by Dassderdie** [comment]
> I don't think deleting exercises that fail the migration should be deleted. This would be a very bad time when you as a user want to use the exercise again, but it's suddenly not there anymore, and hard to impossible to recover.
> 
> Also, what changes do you have in mind that would have a failure as an expected outcome?

I believe currently any use of the `impossible-migration` would lead to a server error. At least I couldn't find a catch statement in the code.

**Comment by benn02** [comment]
If one sent a vehicle to a hospital with personal not loaded, this was allowed and is now forbidden. When the migration applies the actions it fails. This is the current case that is happening. It would also be fine to not apply the actions in this instance, but any fix that stops the server from crashing is acceptable in my opinion.
 One also has to be aware of future changes, so no future change leads to a crash (if it is legitimate) but rater to a notice.

**Comment by ClFeSc** [comment]
> I believe currently any use of the `impossible-migration` would lead to a server error. At least I couldn't find a catch statement in the code.

This is intentional. It was meant so that admins of backends/databases that contain exercises that raise an `impossible-migration` are warned (due to the server not starting) and have to manually decide whether they want to delete the exercises, try to fix them manually, or downgrade to keep the exercises.

I don't think silently deleting exercises or dropping actions would be the expected outcome. But if you think this is the right call, go ahead. Currently, we should be the only ones with a deployed version, so it should be manageable.

> One also has to be aware of future changes, so no future change leads to a crash (if it is legitimate) but rater to a notice.

I agree with that, there could be a nicer notice than a crash when this happens.
