### ISSUE TITLE
HPI-sam is at its git lfs bandwidth limit because of the pipeline

### ISSUE THREAD

**Issue by Greenscreen23** [hpi-sam/digital-fuesim-manv#728]

**Comment by Dassderdie** [comment]
What about caching the lfs files? https://github.com/nschloe/action-cached-lfs-checkout

**Comment by Greenscreen23** [comment]
> What about caching the lfs files? https://github.com/nschloe/action-cached-lfs-checkout

We thought about that, but because these image files rarely change and could be scaled down to ~0.5MB total, we thought it would be easier to just put them in the repo

**Comment by Dassderdie** [comment]
> We thought about that, but because these image files rarely change and could be scaled down to ~0.5MB total, we thought it would be easier to just put them in the repo.
> 
> They also should not change, so git should not duplicate them right?

1.  You should document this assumption somewhere. I could imagine we replace them one day with higher resolution images or edit them a bit for special occasions etc.

2. If more images get added you would run into the same problem you have now.
