### ISSUE TITLE
Report Activity

### ISSUE THREAD

**Issue by lukasrad02** [hpi-sam/digital-fuesim-manv#761]
Create an activity that add radiograms with reported information

### Acceptance Criteria: 

- [x] The activity gets passed the type of the collected information and an empty radiogram for that type
- [x] The activity emits an event with the given type. This event also contains the id of the activity
    - All behaviors check whether they can provide the needed information
- [x] After a tick, the activity adds the radiogram to the list of radiograms in the state

### Depends on:

- #751

**Comment by Greenscreen23** [comment]
Waiting for #778
