### ISSUE TITLE
Answer count queries

### ISSUE THREAD

**Issue by lukasrad02** [hpi-sam/digital-fuesim-manv#763]
Answer queries for personnel, vehicles, patients and material in a simulated region

### Acceptance Criteria:

- [ ] The reports behavior answers queries for the amount of personnel
- [ ] The reports behavior answers queries for the amount of vehicles
- [ ] The reports behavior answers queries for the amount of patients
- [ ] The reports behavior answers queries for the amount of material

### Depends on:

- #762

**Comment by Nils1729** [comment]
I think the responsibilities should be split to the specific behaviors. In particular

* number of patients should be reported by the treat patients behavior as it is the one counting them in the domain
* personnel,material and vehicles could be reported by the assign leader behavior
