### ISSUE TITLE
Import tests

### ISSUE THREAD

**Issue by lukasrad02** [hpi-sam/digital-fuesim-manv#765]
Add a test that tries to import exercises to check for migration errors.

**Comment by ClFeSc** [comment]
See #517 in this context.

**Comment by lukasrad02** [comment]
> See #517 in this context.

Thank you for the pointer! I think this can help us writing test that import an exercise, however, it's not exactly what we want.

I'm sorry, the issue itself is not that descriptive, but we thought about some test that receives a large amount of exported exercises, trying to cover as much actions and state versions as possible and just try to import them, asserting that the import works but (opposite to your PR) not asserting that the imported state should be equal to some predefined value.

The reason for this is that we had a lot failures in production recently, that have all been caused by missing or incomplete migrations after a change to the `shared` package. In all these cases, the failure already occurred during the import when re-applying actions from the history or when validating the final state. Wrong imports (i.e., the import completed without errors and one can join the exercises) did not happen yet, as far as we know.

Of course, the failure described above could be prevented by manually trying to import old exercises, but therefore, we'd need these old exercises in the first place. So the most important part of this issue is to create such a set of exercises that can be used for either manual or automated testing. And if such a set exist, it would be easy to write an automated test that only verify they can be imported. Doing assertions on the imported state would increase the maintenance needs, since the expected states would have to be updated with every new migration.

Do you think this sounds reasonable, or would you suggest another approach?

**Comment by ClFeSc** [comment]
No, this sounds completely reasonable. I don't think we had many problems with imports that crashed a reducer and rather feared that we might introduce semantical errors, and such a test would force us to run the migration where we could check for such problems. In the current situation, however, I can see that your approach makes more sense, and it should be easier to implement.
