### ISSUE TITLE
Enforce branch protection

### ISSUE THREAD

**Issue by Nils1729** [hpi-sam/digital-fuesim-manv#773]
We need to update the tests-done job. Currently, because [skipped checks report as successful](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks) (?!), our branch protection rules do not prevent merging.

**Comment by lukasrad02** [comment]
@Nils1729 is it on purpose that the `dependencies` job is required for `tests-done`?

As far as I remember, the dependencies were allowed to fail to prevent blocking the whole development due to one single vulnerable dependency...

**Comment by Nils1729** [comment]
> @Nils1729 is it on purpose that the `dependencies` job is required for `tests-done`?
> 
> As far as I remember, the dependencies were allowed to fail to prevent blocking the whole development due to one single vulnerable dependency...

I did not think about that when I introduced the job. You can omit it.
