### ISSUE TITLE
Migration tests might fail if two PRs add new scenarios at the same time

### ISSUE THREAD

**Issue by lukasrad02** [hpi-sam/digital-fuesim-manv#861]
If there are multiple PRs open at the same time and both add new test scenarios, the PR that added the scenarios last includes all other scenarios. Therefore, migration tests fail in this branch as the required actions, models, ... are not part of the code of this PR.

**Comment by Greenscreen23** [comment]
I believe this has been fixed by using branches in the subrepo as well
