### ISSUE TITLE
Highlight which personnel and material belongs to the currently selected vehicle

### ISSUE THREAD

**Issue by lukasrad02** [hpi-sam/digital-fuesim-manv#882]
In a large exercise, it can be hard to keep track which personnel and material belongs to which vehicle. The elements have a text showing the name of the vehicle they belong to, but it is rather small and therefore hard to see. Therefore, when selecting a vehicle, the personnel and material belonging to it should be highlighted, for example, by a colored outline.

This issue could make use of a highlighting solution on the map developed in #798

**Comment by benn02** [comment]
This should only apply to trainers, not to participants
