### ISSUE TITLE
Add transfer button to vehicles tab

### ISSUE THREAD

**Issue by benn02** [hpi-sam/digital-fuesim-manv#895]
It should be possible to initiate transfer related activities from the vehicles tab.

For that, another button should be added to the interface created in *Add vehicles tab to simulated region popup/modal*.

### Aceeptance criteria

- [ ] There is a "Transfer" button in the vehicles tab in the same location as the load, unload, move and remove buttons
- [ ] When the button is clicked:
    - [ ] It adds a TransferBehavior to the current region if there isn't already one
    - [ ] It focuses the user interface of this behavior in the behaviors tab
    - [ ] It selects the vehicle in the user interface for a new TransferVehicleRequestEvent

### Depends on

- #892
- #891

**Comment by Greenscreen23** [comment]
Merged with #894
