### ISSUE TITLE
Missing transfer connection radiogram send on configuration

### ISSUE THREAD

**Issue by Nils1729** [hpi-sam/digital-fuesim-manv#931]
How to reproduce:

* Create a new exercise
* Drag a green and a red region to the map
* Open the behavior tab on the red region
* In the vehicle request event, switch from trainees to the green region and back
* start the exercise

Observed behavior:

* A MissingTransferConnectionRadiogram is sent

Expected behavior:

* No Radiogram is sent

**Comment by Greenscreen23** [comment]
Not reproducible after 6f22e9f75024c72ea31a3d1d3cf39e198d0e7f0a, I will investigate this commit

**Comment by Greenscreen23** [comment]
Fixed by #911
