### ISSUE TITLE
Create Manage Patient Transport Behavior

### ISSUE THREAD

**Issue by lukasrad02** [hpi-sam/digital-fuesim-manv#970]
There should be a new behavior that manages the transport of patients from simulated regions to hospitals. It either manages multiple alien simulated regions or just its own.

### Acceptance criteria:

- [x] The behavior can be configured with either a list of alien simulated regions or just its own region to manage
- [ ] For each alien simulated region that it is managing the current count of patients can be entered via a UI at any time
- [x] For its own simulated region it acquires that data similar to the report behavior
- [x] An interval in which requests for patient numbers are to be made can be set
- [x] After each interval the behavior sends a radiogram that asks for new patient data 
    - [ ] The radiogram has a link to the Input form in the behavior tab
- [ ] The Transport can be started or stopped in the UI - the default is stopped
- [x] The behavior can be configured with a SK up to which the transport takes place.
- [x] The behavior sends events when the last patient in a category has been sent to a hospital.
- [x] It can be configured with a Simulated region to request vehicles from
- [x] It can be configured with a send and a retry delay
- [x] It keeps internal bookkeeping of the patients expected to be currently in a simulated region and expected to be in a simulated region if all vehicles arrived and the number of patients transported to hospital per region per category
- [ ] Every send delay it tries to send a vehicle to the region with the most expected remaining patients (assuming all sent vehicles will arrive) of the highest category it then instantly updates that number. 
- [ ] If the send fails it retries once after the retry delay if that fails it adjusts the internal bookkeeping and does not retry the send
- [x] If new patient data is put into the behavior that does not match with the data of the internal bookkeeping the internal bookkeeping is adjusted accordingly

### Depends on

- #962

**Comment by Greenscreen23** [comment]
Some notes:
- We've removed the "retry once" step, as we felt like it would introduce too much complexity
- The behavior does not select a region that is in need, but instead tries to send one vehicle to each region in need, so it is not blocked if one transfer connection is missing
