### ISSUE TITLE
Create TO Template

### ISSUE THREAD

**Issue by lukasrad02** [hpi-sam/digital-fuesim-manv#972]
There should be a simulated region template for transport management.

### Acceptance criteria

- [ ] The template is named "Transportorganisation"
- [ ] It uses an outline color that is not used by any existing template
- [ ] It is pre-configured with the Manage patient transport behavior and the reports behavior and the choose leader behavior

### Depends on

- #970

**Comment by Nils1729** [comment]
Also add a `TransferToHospitalBehavior` to the PA template please.
